services:
  - type: web
    name: medical-exam-prep
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-large
      - key: LLM_MODEL
        value: gpt-4o
      - key: MAX_TOKENS
        value: 4096
      - key: TEMPERATURE
        value: 0.7
      - key: CHUNK_SIZE
        value: 1000
      - key: CHUNK_OVERLAP
        value: 200
      - key: EMBEDDING_BATCH_SIZE
        value: 100
      - key: VALIDATION_CONFIDENCE_THRESHOLD
        value: 80
      - key: MAX_REGENERATION_ATTEMPTS
        value: 2